# Generated by Django 5.1.15 on 2026-07-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_project_comment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance'), ('Product Management', 'Product Management'), ('IT', 'IT'), ('HR', 'HR'), ('Operations', 'Operations')], default='Engineering', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
    ]
